// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const isMigrating = process.argv.some((arg) => arg.includes("migrate"));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: isMigrating ? env("MIGRATION_URL") : env("DATABASE_URL"),
  },
});
